# Generated by Django 2.1.7 on 2019-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyfe', '0004_remove_myuser_password_confirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
