# Generated by Django 2.2.5 on 2020-11-12 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyfe', '0005_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='grape',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='year',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
